name: Build and Deploy ASP.NET MVC App to Azure

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: my-mvc-app                # must match webAppName in your ARM template
  AZURE_RESOURCE_GROUP: Github-Copilot-Challenges    # replace with your resource group name
  AZURE_REGION: eastus                         # or your preferred region

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy ARM template
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        template: deploy/deploy.json
        parameters: webAppName=${{ env.AZURE_WEBAPP_NAME }} location=${{ env.AZURE_REGION }}

    - name: Publish to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        package: ${{ github.workspace }}/MyMvcApp/bin/Release/net8.0/publish

    - name: Build and publish .NET app
      run: |
        dotnet publish MyMvcApp/MyMvcApp.csproj -c Release -o ${{ github.workspace }}/MyMvcApp/bin/Release/net8.0/publish